package com.infosung.atomic.oauth.api

enum class OauthProviderCapability {
  AUTHORIZATION_URL,
  EXCHANGE_TOKEN,
  REFRESH_TOKEN,
  REVOKE_TOKEN,
  RESOLVE_IDENTITY_WITH_ID_TOKEN,
  RESOLVE_IDENTITY_WITH_USER_INFO,
  RESOLVE_IDENTITY_ID_ONLY,
  RESOLVE_IDENTITY_BASIC_PROFILE,
  RESOLVE_IDENTITY_FULL_PROFILE,
}
