# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.3.10"
jupiter = "6.0.1"
spring-cloud = "2025.1.0"
java = "25"
aop = "4.0.0-M2"

jjwt = "0.12.6"
jdk18on = "1.82"

springboot = "4.0.3"

[libraries]
# spring boot
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-restclient = { module = "org.springframework.boot:spring-boot-starter-restclient" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop", version.ref = "aop" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-actuator-test = { module = "org.springframework.boot:spring-boot-starter-actuator-test" }
spring-boot-starter-restclient-test = { module = "org.springframework.boot:spring-boot-starter-restclient-test" }
spring-boot-starter-security-test = { module = "org.springframework.boot:spring-boot-starter-security-test" }
spring-boot-starter-validation-test = { module = "org.springframework.boot:spring-boot-starter-validation-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }

# spring cloud
spring-cloud-starter-circuitbreaker-resilience4j = { module = "org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j" }
spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }

# kotlin
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }

# jackson
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }

# micrometer
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }

# testcontainers
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }

# jupiter
jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "jupiter" }
jupiter-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "jupiter" }
jupiter-bom = { group = "org.junit", name = "junit-bom", version.ref = "jupiter" }

# jwt
jjwt-api = { group = "io.jsonwebtoken", name = "jjwt-api", version.ref = "jjwt" }
jjwt-impl = { group = "io.jsonwebtoken", name = "jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { group = "io.jsonwebtoken", name = "jjwt-jackson", version.ref = "jjwt" }
bouncycastle = { group = "org.bouncycastle", name = "bcpkix-jdk18on", version.ref = "jdk18on" }

# oauth
google-api-client = { group = "com.google.api-client", name = "google-api-client", version = "2.8.1" }

# claud
anthropic = { group = "com.anthropic", name = "anthropic-java", version = "2.10.0" }

# deepl
deepl = { group = "com.deepl.api", name = "deepl-java", version = "1.14.0" }

[bundles]

[plugins]
springboot = { id = "org.springframework.boot", version.ref = "springboot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
