package com.infosung.atomic.app.oauth.application.exception

enum class OauthRedirectErrorCode {
  OAUTH_REDIRECT_INVALID_REQUEST,
  OAUTH_CALLBACK_INVALID_REQUEST,
  OAUTH_PROVIDER_REMOTE_FAILURE,
  OAUTH_APPLE_CALLBACK_POST_ONLY,
  OAUTH_REDIRECT_CONFIGURATION_INVALID,
  OAUTH_RELAY_CODE_INVALID_REQUEST,
}
