CREATE TABLE IF NOT EXISTS image (
  id VARCHAR(255) NOT NULL,
  bucket VARCHAR(255) NOT NULL,
  service_name VARCHAR(255) NOT NULL,
  storage_service VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
  uploader_id VARCHAR(255) NULL,
  storage_type VARCHAR(255) NOT NULL,
  file_name TEXT NULL,
  thumbnail_file_name TEXT NULL,
  url TEXT NOT NULL,
  thumbnail_url TEXT NULL,
  width INT NULL,
  height INT NULL,
  file_size BIGINT NOT NULL,
  thumbnail_width INT NULL,
  thumbnail_height INT NULL,
  thumbnail_file_size BIGINT NULL,
  delete_recovery_claim_token VARCHAR(255) NULL,
  delete_recovery_claimed_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_image_service_storage (service_name, storage_service),
  KEY idx_image_status_created_at (status, created_at),
  KEY idx_image_status_claim_created_at (status, delete_recovery_claim_token, created_at)
) ENGINE=InnoDB;
