CREATE TABLE service_version (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  main_version NUMBER(10) NOT NULL,
  minor_version NUMBER(10) NOT NULL,
  patch_number NUMBER(10) NOT NULL,
  require_update NUMBER(1) DEFAULT 0 NOT NULL,
  store_available NUMBER(1) DEFAULT 1 NOT NULL,
  platform VARCHAR2(255 CHAR) NOT NULL,
  service VARCHAR2(255 CHAR) NOT NULL,
  store_url CLOB NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_service_version_service_platform_semver
    UNIQUE (service, platform, main_version, minor_version, patch_number)
);

CREATE INDEX idx_service_version_service_platform_required_update
  ON service_version (
    service,
    platform,
    require_update,
    main_version DESC,
    minor_version DESC,
    patch_number DESC
  );
